### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by alexlafroscia** [alexlafroscia/vim-ember-cli#1]
A list of things that I'm planning to do with this

---

**Projectionist**
- [ ] Set Projectionist config for Ember defaults

**Ember Commands**
- [x] Auto-complete types and names (where applicable)
- [x] Dynamically generate list of types (maybe)
- [ ] Better error parsing from Dispatch 

**Omni Complete**
- [x] Handlebars: Components
- [x] Handlebars: Helpers

**Snippets**
- [ ] Handlebars: Common tags
